<!-- Generated by Cursor -->
<template>
    <div class="mb-6">
      <table class="min-w-full bg-gray-50 shadow rounded">
        <thead>
          <tr>
            <th class="py-3 px-4 border-b text-left text-gray-600 w-1/4">
              {{ t('automaticAdjustment.table.headers.notificationType') }}
            </th>
            <th class="py-3 px-4 border-b text-left text-gray-600 w-2/4">
              {{ t('automaticAdjustment.table.headers.beforeAdjustment') }}
            </th>
            <th class="py-3 px-4 border-b text-left text-gray-600 w-1/4">
              {{ t('automaticAdjustment.table.headers.afterAdjustment') }}
            </th>
          </tr>
        </thead>
        <tbody>
          <!-- Zalo SMS Before -->
          <tr class="hover:bg-gray-50">
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <img src="../../../src/assets/images/brand/brand-07.png" alt="Zalo" class="w-5 h-5 mr-2" />
                <span class="font-medium">
                  {{ t('automaticAdjustment.table.rows.zaloSms-before') }}
                </span>
              </div>
            </td>
            <td class="py-3 px-4 border-b">
              {{ t('automaticAdjustment.table.rows.description-sms-downgrade') }}
            </td>
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <input 
                  type="checkbox" 
                  v-model="notifications.zaloSmsBefore" 
                  class="form-check-input"
                >
              </div>
            </td>
          </tr>

          <!-- Zalo SMS After -->
          <tr class="hover:bg-gray-50">
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <img src="../../../src/assets/images/brand/brand-07.png" alt="Zalo" class="w-5 h-5 mr-2" />
                <span class="font-medium">
                  {{ t('automaticAdjustment.table.rows.zaloSms-after') }}
                </span>
              </div>
            </td>
            <td class="py-3 px-4 border-b">
              {{ t('automaticAdjustment.table.rows.description-sms-upgrade') }}
            </td>
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <input 
                  type="checkbox" 
                  v-model="notifications.zaloSmsAfter" 
                  class="form-check-input"
                >
              </div>
            </td>
          </tr>

          <!-- Email Before -->
          <tr class="hover:bg-gray-50">
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <svg class="w-5 h-5 mr-2 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <span class="font-medium">
                  {{ t('automaticAdjustment.table.rows.email-before') }}
                </span>
              </div>
            </td>
            <td class="py-3 px-4 border-b">
              {{ t('automaticAdjustment.table.rows.description-email-downgrade') }}
            </td>
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <input 
                  type="checkbox" 
                  v-model="notifications.emailBefore" 
                  class="form-check-input"
                >
              </div>
            </td>
          </tr>

          <!-- Email After -->
          <tr class="hover:bg-gray-50">
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <svg class="w-5 h-5 mr-2 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                        d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <span class="font-medium">
                  {{ t('automaticAdjustment.table.rows.email-after') }}
                </span>
              </div>
            </td>
            <td class="py-3 px-4 border-b">
              {{ t('automaticAdjustment.table.rows.description-email-upgrade') }}
            </td>
            <td class="py-3 px-4 border-b">
              <div class="flex items-center">
                <input 
                  type="checkbox" 
                  v-model="notifications.emailAfter" 
                  class="form-check-input"
                >
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </template>
  
  <script setup lang="ts">
  import { ref, watch } from 'vue'
  import { useI18nGlobal } from '@/i18n'

  const { t } = useI18nGlobal()

  const notifications = ref({
    zaloSmsBefore: false,
    zaloSmsAfter: false,
    emailBefore: false,
    emailAfter: false
  })

  const emit = defineEmits<{
    (e: 'update:notifications', value: {
      zaloSmsBefore: boolean;
      zaloSmsAfter: boolean;
      emailBefore: boolean;
      emailAfter: boolean;
    }): void;
  }>()

  watch(notifications, (newValue) => {
    emit('update:notifications', newValue)
  }, { deep: true })
  </script>

  <style scoped>
  .form-check-input {
    width: 1rem;
    height: 1rem;
    margin-top: 0.25rem;
    vertical-align: top;
    background-color: #fff;
    background-repeat: no-repeat;
    background-position: center;
    background-size: contain;
    border: 1px solid rgba(0, 0, 0, 0.25);
    appearance: none;
    print-color-adjust: exact;
    border-radius: 0.25em;
    transition: background-color 0.15s ease-in-out, 
                background-position 0.15s ease-in-out, 
                border-color 0.15s ease-in-out, 
                box-shadow 0.15s ease-in-out;
  }

  .form-check-input:checked {
    background-color: #0d6efd;
    border-color: #0d6efd;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'%3e%3cpath fill='none' stroke='%23fff' stroke-linecap='round' stroke-linejoin='round' stroke-width='3' d='M6 10l3 3l6-6'/%3e%3c/svg%3e");
  }

  .form-check-input:focus {
    border-color: #86b7fe;
    outline: 0;
    box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
  }

  tr:hover {
    @apply bg-gray-50 transition-colors duration-150;
  }
  </style>