<!-- Generated by Cursor -->
<template>
    <div class="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div class="bg-white rounded-lg shadow-lg w-96 p-6">
        <div class="flex justify-between items-center mb-4">
          <h3 class="text-lg font-medium text-gray-900">
            {{ isEditing ? 'Chỉnh Sửa Cài Đặt' : 'Thêm Cài Đặt' }}
          </h3>
          <button @click="$emit('close')" class="text-gray-600 hover:text-gray-800 focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
  
        <form @submit.prevent="handleSubmit">
          <div class="mb-4">
            <label class="block text-gray-700">Tên Cài Đặt:</label>
            <input 
              type="text" 
              v-model="formData.adjustmentName" 
              class="w-full border border-gray-300 rounded px-4 py-2 mt-1" 
              required
            >
          </div>
  
          <div class="mb-4">
            <label class="block text-gray-700">Tần Suất Tái Tính Hạng:</label>
            <select 
              v-model="formData.frequency" 
              class="w-full border border-gray-300 rounded px-4 py-2 mt-1" 
              required
            >
              <option value="" disabled>-- Chọn Tần Suất --</option>
              <option 
                v-for="option in FREQUENCY_OPTIONS" 
                :key="option.value" 
                :value="option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </div>
  
          <div class="mb-4">
            <label class="block text-gray-700">Mô Tả Tái Tính:</label>
            <textarea 
              v-model="formData.recalculationDescription" 
              class="w-full border border-gray-300 rounded px-4 py-2 mt-1" 
              required
            ></textarea>
          </div>
  
          <div class="mb-4">
            <label class="block text-gray-700">Kênh Thông Báo:</label>
            <select 
              v-model="formData.channel" 
              class="w-full border border-gray-300 rounded px-4 py-2 mt-1" 
              required
            >
              <option value="" disabled>-- Chọn Kênh Thông Báo --</option>
              <option 
                v-for="option in CHANNEL_OPTIONS" 
                :key="option.value" 
                :value="option.value"
              >
                {{ option.label }}
              </option>
            </select>
          </div>
  
          <div class="mb-4">
            <label class="block text-gray-700">Mô Tả Thông Báo:</label>
            <textarea 
              v-model="formData.notificationDescription" 
              class="w-full border border-gray-300 rounded px-4 py-2 mt-1" 
              required
            ></textarea>
          </div>
  
          <div class="flex justify-end">
            <button 
              type="submit" 
              class="bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700 focus:outline-none"
            >
              Lưu
            </button>
          </div>
        </form>
      </div>
    </div>
  </template>
  
  <script lang="ts">
  import { defineComponent, reactive, watch } from 'vue'
  import type { PropType } from 'vue'
  import { 
    type AdjustmentForm, 
    defaultAdjustmentForm,
    FREQUENCY_OPTIONS,
    CHANNEL_OPTIONS
  } from '@/data/autoleveladjustments'
  
  export default defineComponent({
    name: 'AdjustmentModal',
  
    props: {
      isEditing: {
        type: Boolean,
        default: false
      },
      initialData: {
        type: Object as PropType<Partial<AdjustmentForm>>,
        default: () => ({})
      }
    },
  
    emits: ['save', 'close'],
  
    setup(props, { emit }) {
      const formData = reactive<AdjustmentForm>({...defaultAdjustmentForm})
  
      watch(() => props.initialData, (newData) => {
        Object.assign(formData, {...defaultAdjustmentForm, ...newData})
      }, { deep: true })
  
      const handleSubmit = () => {
        emit('save', {...formData})
      }
  
      return {
        formData,
        handleSubmit,
        FREQUENCY_OPTIONS,
        CHANNEL_OPTIONS
      }
    }
  })
  </script>
  
  <style scoped>
  .modal-enter-active,
  .modal-leave-active {
    transition: opacity 0.3s ease;
  }
  
  .modal-enter-from,
  .modal-leave-to {
    opacity: 0;
  }
  </style>