<!-- Generated by Cursor -->
<template>
  <div class="bg-white p-6 rounded-lg shadow-md">
    <div class="flex justify-between items-center mb-4">
      <h2 class="text-lg font-semibold">{{ t('membershipTable.title') }}</h2>
      <div class="flex items-center space-x-4">
        <!-- Search input và Export button hiện tại -->
        <div class="relative w-full">
          <input 
            type="text" 
            v-model="searchTerm"
            class="w-full p-2 border rounded-lg pr-8" 
            :placeholder="t('membershipTable.search.placeholder')"
          >
          <span v-if="searchLoading" class="absolute right-2 top-1/2 -translate-y-1/2">
            <a-spin :size="small" />
          </span>
        </div>
        <button 
          @click="handleExport"
          :disabled="exporting"
          class="bg-green-600 text-white py-2 px-4 rounded-lg disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ exporting ? 'Exporting...' : 'Export Excel' }}
        </button>
      </div>
    </div>
    <table class="w-full border-collapse border border-gray-300">
      <thead class="bg-gray-100">
        <tr>
          <th class="border border-gray-300 p-2">{{ t('membershipTable.table.headers.customerName') }}</th>
          <th class="border border-gray-300 p-2">{{ t('membershipTable.table.headers.phoneNumber') }}</th>
          <th class="border border-gray-300 p-2">
            {{ t(`membershipTable.tabs.${tab}`) }}
          </th>
          <th class="border border-gray-300 p-2">{{ t('membershipTable.table.headers.platformWebsite') }}</th>
          <template v-if="tab === 'date-join-member'">
            <th class="border border-gray-300 p-2">{{ t('membershipTable.table.headers.memberLevel') }}</th>
          </template>
          <th class="border border-gray-300 p-2">{{ t('membershipTable.table.headers.actions') }}</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="member in filteredMembers" :key="member.membershipId">
          <td class="border border-gray-300 p-2">{{ member.fullName }}</td>
          <td class="border border-gray-300 p-2">{{ member.mainPhoneNumber }}</td>
          <td class="border border-gray-300 p-2">
            {{ formatDate(tab === 'date-join-member' ? member.registeredTime : member.birthday) }}
          </td>
          <td class="border border-gray-300 p-2">{{ getWebsiteName(member.websiteId) }}</td>
          <template v-if="tab === 'date-join-member'">
            <td class="border border-gray-300 p-2">{{ member.levelName }}</td>
          </template>
          <td class="border border-gray-300 p-2">
            <div class="flex gap-2">
              <button @click="handleView(member)" class="bg-blue-600 text-white py-1 px-2 rounded-lg">
                {{ t('membershipTable.actions.edit') }}
              </button>
              <button @click="handleHistory(member)" class="bg-green-600 text-white py-1 px-2 rounded-lg">
                {{ t('membershipTable.actions.history') }}
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <!-- Enhanced Member Details Modal -->
    <div v-if="selectedMember && activeModal === 'details'" class="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-9999">
      <div class="bg-white rounded-xl shadow-2xl w-[800px] max-h-[90vh] overflow-hidden relative animate-modal-enter">
        <!-- Modal Header -->
        <div class="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-2 flex justify-between items-center">
          <h2 class="text-xl font-bold text-white">{{ t('membershipTable.modal.details.title') }}</h2>
          <button 
            @click="closeModal"
            class="text-white/80 hover:text-white transition-colors"
          >
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Modal Content -->
        <div class="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <!-- Basic Information -->
            <div class="bg-gray-50 p-6 rounded-lg shadow-sm">
              <h3 class="font-semibold text-lg text-gray-800 mb-4 pb-2 border-b border-gray-200">
                {{ t('membershipTable.modal.details.basicInfo.title') }}
              </h3>
              <div class="space-y-4">
                <div class="flex flex-col">
                  <span class="text-sm text-gray-500">{{ t('membershipTable.modal.details.basicInfo.fullName') }}</span>
                  <span class="text-gray-800 font-medium">{{ selectedMember.fullName }}</span>
                </div>
                
                <!-- Editable Phone Number -->
                <div class="flex flex-col">
                  <span class="text-sm text-gray-500">{{ t('membershipTable.modal.details.basicInfo.phoneNumber') }}</span>
                  <div class="flex items-center gap-2">
                    <input 
                      v-if="isEditing && editedMember"
                      v-model="editedMember.mainPhoneNumber"
                      type="text"
                      class="w-full p-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                    />
                    <span v-else class="text-gray-800 font-medium">{{ selectedMember.mainPhoneNumber }}</span>
                    <button 
                      @click="toggleEdit"
                      class="text-blue-600 hover:text-blue-700"
                    >
                      <span v-if="isEditing">Save</span>
                      <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                      </svg>
                    </button>
                  </div>
                </div>

                <!-- Editable Address -->
                <div class="flex flex-col">
                  <span class="text-sm text-gray-500">{{ t('membershipTable.modal.details.basicInfo.address') }}</span>
                  <div class="flex items-center gap-2">
                    <textarea 
                      v-if="isEditing && editedMember"
                      v-model="editedMember.defaultAddress"
                      class="w-full p-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
                      rows="2"
                    ></textarea>
                    <span v-else class="text-gray-800 font-medium">{{ selectedMember.defaultAddress || 'N/A' }}</span>
                  </div>
                </div>
                <!-- <div class="flex flex-col">
                  <span class="text-sm text-gray-500">Platform Website</span>
                  <span class="text-gray-800 font-medium">{{ selectedMember.platformWebsite }}</span>
                </div> -->
              </div>
            </div>

            <!-- Date Information -->
            <div class="bg-gray-50 p-6 rounded-lg">
              <h3 class="font-semibold text-lg text-gray-800 mb-4 pb-2 border-b">
                {{ t(`membershipTable.modal.details.${tab === 'date-join-member' ? 'membershipInfo.title' : 'birthInfo.title'}`) }}
              </h3>
              <div class="space-y-4">
                <template v-if="tab === 'date-join-member'">
                  <!-- <div class="flex flex-col">
                    <span class="text-sm text-gray-500">Join Date Range</span>
                    <span class="text-gray-800 font-medium">
                      {{ formatDateRange(selectedMember.startDate || '', selectedMember.endDate || '') }}
                    </span>
                  </div> -->
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-500">Order Point</span>
                    <span class="text-gray-800 font-medium">{{ selectedMember.totalOrder }}</span>
                  </div>
                  <!-- <div class="flex flex-col">
                    <span class="text-sm text-gray-500">Member Downgrade Month</span>
                    <span class="text-gray-800 font-medium">{{ formatMonth(selectedMember.memberDowngradeMonth || '') }}</span>
                  </div> -->
                </template>
                <template v-else>
                  <div class="flex flex-col">
                    <span class="text-sm text-gray-500">Date of Birth</span>
                    <span class="text-gray-800 font-medium">{{ formatMonth(selectedMember.birthday || '') }}</span>
                  </div>
                </template>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Footer -->
        <div class="bg-gray-50 px-6 py-2 border-t flex justify-end gap-3">
          <button 
            v-if="isEditing"
            @click="cancelEdit"
            class="bg-gray-500 hover:bg-gray-600 text-white px-5 py-1 rounded-lg transition-colors"
          >
            {{ t('membershipTable.modal.details.buttons.cancel') }}
          </button>
          <button 
            v-if="isEditing"
            @click="saveChanges"
            class="bg-blue-600 hover:bg-blue-700 text-white px-5 py-1 rounded-lg transition-colors"
          >
            {{ t('membershipTable.modal.details.buttons.save') }}
          </button>
          <button 
            v-else
            @click="closeModal"
            class="bg-gray-500 hover:bg-gray-600 text-white px-6 py-2 rounded-lg transition-colors"
          >
            {{ t('membershipTable.modal.details.buttons.close') }}
          </button>
        </div>
      </div>
    </div>

    <!-- Order History Modal -->
    <div v-if="selectedMember && activeModal === 'history'" class="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-[99] mt-[70px]">
      <div class="bg-white rounded-xl shadow-2xl w-[800px] max-h-[calc(100vh-70px)] overflow-hidden relative animate-modal-enter">
        <!-- Modal Header -->
        <div class="bg-gradient-to-r from-green-600 to-green-700 px-6 py-2 flex justify-between items-center">
          <h2 class="text-xl font-bold text-white">Order History</h2>
          <button 
            @click="closeModal"
            class="text-white/80 hover:text-white transition-colors"
          >
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <!-- Modal Content -->
        <div class="p-6 overflow-y-auto max-h-[calc(100vh-250px)]">
          <div class="space-y-6">
            <!-- Purchase History -->
            <div class="bg-gray-50 p-6 rounded-lg">
              <h3 class="font-semibold text-lg text-gray-800 mb-4">{{ t('profileManagement.orderHistory.title') }}</h3>
              <div class="overflow-x-auto">
                <table class="w-full border-collapse border border-gray-300">
                  <thead class="bg-gray-100">
                    <tr>
                      <th class="border p-2">{{ t('profileManagement.orderHistory.headers.date') }}</th>
                      <th class="border p-2">{{ t('profileManagement.orderHistory.headers.orderId') }}</th>
                      <th class="border p-2">{{ t('profileManagement.orderHistory.headers.products') }}</th>
                      <th class="border p-2">{{ t('profileManagement.orderHistory.headers.total') }}</th>
                      <th class="border p-2">{{ t('profileManagement.orderHistory.headers.status') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="order in orderHistory || []" :key="order.order_id">
                      <td class="border p-2">{{ formatDate(order.order_date) }}</td>
                      <td class="border p-2">#{{ order.order_id }}</td>
                      <td class="border p-2">
                        <div v-for="item in order.items" :key="item.product_id" class="mb-1">
                          {{ item.order_item_name }} (x{{ item.product_quantity }})
                        </div>
                      </td>
                      <td class="border p-2">{{ formatCurrency(order.order_total) }}</td>
                      <td class="border p-2">
                        <span :class="getOrderStatusClass(order.order_status)">
                          {{ order.order_status }}
                        </span>
                      </td>
                    </tr>
                    <tr v-if="!orderHistory?.length">
                      <td colspan="5" class="text-center p-4 text-gray-500">No orders found</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <!-- Point History -->
            <div class="bg-gray-50 p-6 rounded-lg mt-6">
              <h3 class="font-semibold text-lg text-gray-800 mb-4">{{ t('membershipTable.pointHistory.title') }}</h3>
              <div class="overflow-x-auto">
                <table class="w-full border-collapse border border-gray-300">
                  <thead class="bg-gray-100">
                    <tr>
                      <th class="border p-2">{{ t('membershipTable.pointHistory.headers.date') }}</th>
                      <th class="border p-2">{{ t('membershipTable.pointHistory.headers.orderId') }}</th>
                      <th class="border p-2">{{ t('membershipTable.pointHistory.headers.action') }}</th>
                      <th class="border p-2">{{ t('membershipTable.pointHistory.headers.points') }}</th>
                      <th class="border p-2">{{ t('membershipTable.pointHistory.headers.totalPoints') }}</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr v-for="point in pointHistory" :key="`${point.orderId}-${point.productId}`">
                      <td class="border p-2">{{ formatDate(new Date(Number(point.dateRecord) * 1000)) }}</td>
                      <td class="border p-2">#{{ point.orderId }}</td>
                      <td class="border p-2">{{ point.action }}</td>
                      <td class="border p-2" :class="point.point > 0 ? 'text-green-600' : 'text-red-600'">
                        {{ point.point > 0 ? '+' : '' }}{{ point.point }}
                      </td>
                      <td class="border p-2">{{ point.totalPoint }}</td>
                    </tr>
                    <tr v-if="!pointHistory.length">
                      <td colspan="5" class="text-center p-4 text-gray-500">
                        {{ t('membershipTable.pointHistory.noData') }}
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Footer -->
        <div class="bg-gray-50 px-6 py-1 border-t flex justify-end">
          <button 
            @click="closeModal"
            class="bg-gray-500 hover:bg-gray-600 text-white px-6 py-1 rounded-lg transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>

    <!-- Thay thế phần pagination cũ bằng a-pagination -->
    <div class="mt-4 flex items-center gap-4 justify-between">
      <span class="text-sm text-gray-600">
        {{ t('membershipTable.pagination.total', { count: totalCount }) }}
      </span>

      <a-pagination
        :current="currentPage"
        :total="totalCount"
        :page-size="pageSize"
        :show-total="false"
        :show-size-changer="true"
        :page-size-options="['10', '20', '50', '100']"
        @change="handlePageChange"
        @showSizeChange="handleSizeChange"
      >
        <template #buildOptionText="props">
          <span>{{ t('membershipTable.pagination.perPage', { count: props.value }) }}</span>
        </template>
      </a-pagination>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useI18nGlobal } from '@/i18n'
import { orderHistoryApi, type Order } from '@/api/services/orderHistoryApi'
import { message } from 'ant-design-vue'
import type { Member } from '@/types/profile'
import { membershipAPI } from '@/api/services/membershipApi'
import { pointHistoryApi, type PointTransaction } from '@/api/services/pointHistoryApi'
import * as XLSX from 'xlsx'
import { getWebsiteName } from '@/api/types/website'

const { t } = useI18nGlobal()

// Props
const props = defineProps<{
  members: Member[]
  loading?: boolean
  tab: string
  filters: Array<{key: string, value: any}>
  currentPage: number
  totalCount: number
  pageSize: number
  sortField?: string
  sortType?: 'ASC' | 'DESC'
}>()

// Emits
const emit = defineEmits<{
  (e: 'update:currentPage', page: number): void
  (e: 'page-change', params: { 
    pageIndex: number
    pageSize: number
    searchParams: Array<{key: string, value: any}>
    sortField?: string
    sortType?: string
  }): void
  (e: 'size-change', size: number): void
  (e: 'filter-change', filters: Array<{key: string, value: any}>): void
}>()

// State
const searchTerm = ref('')
const selectedMember = ref<Member | null>(null)
const activeModal = ref<'details' | 'history' | null>(null)
const isEditing = ref(false)
const editedMember = ref<Member | null>(null)
const orderHistory = ref<Order[]>([])
const pointHistory = ref<PointTransaction[]>([])
const loading = ref(false)
const websites = ref([
  { websiteId: 1, name: 'Website 1' },
  { websiteId: 2, name: 'Website 2' }
])
const exporting = ref(false)
const searchLoading = ref(false)

// Định nghĩa interface cho Member Level
interface MemberLevel {
  id: number
  name: string
}

// Add watcher for search term
watch(searchTerm, debounce(async (newValue: string) => {
  try {
    searchLoading.value = true
    const currentFilters = Array.isArray(props.filters) ? props.filters : []
    
    // Luôn emit page-change, kể cả khi searchTerm rỗng
    emit('page-change', {
      pageIndex: 1,
      pageSize: props.pageSize,
      searchParams: [
        ...currentFilters.filter(f => f.key !== 'fullName'), // Loại bỏ fullName filter cũ nếu có
        ...(newValue.trim() ? [{ // Chỉ thêm fullName filter khi có giá trị search
          key: 'fullName',
          value: newValue.trim()
        }] : [])
      ]
    })
  } finally {
    searchLoading.value = false
  }
}, 300))

// Add debounce utility
function debounce(fn: Function, delay: number) {
  let timeout: NodeJS.Timeout
  return (...args: any[]) => {
    clearTimeout(timeout)
    timeout = setTimeout(() => fn(...args), delay)
  }
}

// Computed
const filteredMembers = computed(() => {
  if (!searchTerm.value) return props.members
  
  return props.members.filter(member => 
    member.fullName.toLowerCase().includes(searchTerm.value.toLowerCase())
  )
})

// Methods
const formatDate = (date: string) => {
  if (!date) return ''
  return new Date(date).toLocaleDateString('vi-VN')
}

const formatMonth = (date: string) => {
  if (!date) return ''
  return new Date(date).toLocaleDateString('vi-VN', { month: 'long', year: 'numeric' })
}

const formatDateRange = (startDate: string, endDate: string) => {
  return `${formatDate(startDate)} - ${formatDate(endDate)}`
}

const formatDateJoinMember = (date: string) => {
  return formatDate(date)
}

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND'
  }).format(amount)
}

const getOrderStatusClass = (status: string) => {
  const statusClasses = {
    'wc-completed': 'text-green-600 bg-green-100',
    'wc-processing': 'text-blue-600 bg-blue-100',
    'wc-cancelled': 'text-red-600 bg-red-100',
    'wc-pending': 'text-yellow-600 bg-yellow-100'
  }
  return `px-2 py-1 rounded-full text-sm ${statusClasses[status] || 'text-gray-600 bg-gray-100'}`
}

const handleView = (member: Member) => {
  selectedMember.value = member
  activeModal.value = 'details'
  emit('view', member)
}

const handleHistory = async (member: Member) => {
  selectedMember.value = member
  activeModal.value = 'history'
  
  if (!member.membershipWebsiteId) {
    message.error('Member Website ID not found')
    return
  }
  try {
    loading.value = true
    const [orderResponse, pointResponse] = await Promise.all([
      orderHistoryApi.getOrderHistory(member.membershipWebsiteId),
      pointHistoryApi.getPointHistory(member.membershipWebsiteId)
    ])
    orderHistory.value = orderResponse.orders
    pointHistory.value = pointResponse.data
  } catch (error) {
    console.error('Error fetching history:', error)
    message.error(t('profileManagement.history.error.fetch'))
  } finally {
    loading.value = false
  }
}

const handlePointHistory = async (member: Member) => {
  if (!member.membershipWebsiteId) {
    message.error('Member Website ID not found')
    return
  }

  try {
    loading.value = true
    const response = await pointHistoryApi.getPointHistory(member.membershipWebsiteId)
    pointHistory.value = response.data
  } catch (error) {
    console.error('Error fetching point history:', error)
    message.error(t('profileManagement.pointHistory.error.fetch'))
  } finally {
    loading.value = false
  }
}

const handleExport = async () => {
  try {
    exporting.value = true
    // Lấy toàn bộ data để export (có thể dùng API riêng để lấy all data)
    let exportData = props.members
    // Nếu đang search thì chỉ export data đã filter
    if (searchTerm.value) {
      exportData = exportData.filter(member => 
        member.fullName.toLowerCase().includes(searchTerm.value.toLowerCase())
      )
    }
    // Format data cho Excel
    const dataToExport = exportData.map(member => ({
      'Customer Name': member.fullName,
      'Email': member.email,
      'Phone': member.mainPhoneNumber,        
      'Address': member.defaultAddress,
      'Level Name': member.levelName,
      'Join Date': member.registeredTime,
      'Website': member.websiteId
    }))

    // Tạo workbook và worksheet
    const wb = XLSX.utils.book_new()
    const ws = XLSX.utils.json_to_sheet(dataToExport)

    // Thêm worksheet vào workbook
    XLSX.utils.book_append_sheet(wb, ws, 'Members')

    // Generate Excel file
    const excelBuffer = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
    const data = new Blob([excelBuffer], { 
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    })
    
    // Download file
    const fileName = `members_${new Date().toISOString().split('T')[0]}.xlsx`
    const link = document.createElement('a')
    link.href = window.URL.createObjectURL(data)
    link.download = fileName
    link.click()

    message.success('Export successful')
  } catch (error) {
    console.error('Error exporting data:', error)
    message.error('Failed to export data')
  } finally {
    exporting.value = false
  }
}

const handlePageChange = (page: number) => {
  emit('update:currentPage', page)
  emit('page-change', {
    pageIndex: page,
    pageSize: props.pageSize,
    searchParams: props.filters,
    sortField: props.sortField,
    sortType: props.sortType
  })
}

const handleSizeChange = (_: number, size: number) => {
  emit('size-change', size)
}

const closeModal = () => {
  selectedMember.value = null
  activeModal.value = null
  orderHistory.value = []
  pointHistory.value = []
  isEditing.value = false
  editedMember.value = null
}

const toggleEdit = () => {
  isEditing.value = !isEditing.value
  if (isEditing.value && selectedMember.value) {
    editedMember.value = { ...selectedMember.value }
  }
}

const cancelEdit = () => {
  isEditing.value = false
  editedMember.value = null
}

const saveChanges = async () => {
  if (!editedMember.value) return
  
  try {
    // Implement save changes logic here
    console.log('Saving changes:', editedMember.value)
    isEditing.value = false
    editedMember.value = null
  } catch (error) {
    message.error('Failed to save changes')
  }
}

const formatLabel = (key: string) => {
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())
}

// Handler cho việc thay đổi level
const handleLevelChange = (value: number | null) => {
  const currentFilters = Array.isArray(props.filters) ? [...props.filters] : []
  
  // Xóa filter level cũ nếu có
  const filtersWithoutLevel = currentFilters.filter(f => f.key !== 'level')
  
  // Thêm filter level mới nếu có giá trị được chọn
  const newFilters = value 
    ? [...filtersWithoutLevel, { key: 'level', value }]
    : filtersWithoutLevel

  emit('filter-change', newFilters)
  
  // Reset về trang 1 khi filter thay đổi
  emit('page-change', {
    pageIndex: 1,
    pageSize: props.pageSize,
    searchParams: newFilters,
    sortField: props.sortField,
    sortType: props.sortType
  })
}

// Style cho level
const getLevelStyle = (levelName: string) => {
  const styles = {
    'Silver': 'text-gray-600 bg-gray-100',
    'Gold': 'text-yellow-600 bg-yellow-100',
    'Platinum': 'text-purple-600 bg-purple-100'
  }
  return `px-2 py-1 rounded-full text-sm ${styles[levelName] || 'text-gray-600 bg-gray-100'}`
}

// Expose necessary methods and properties
defineExpose({
  handleHistory,
  closeModal
})
</script>

<style scoped>
.ant-pagination {
  @apply flex items-center gap-2;
}

.ant-pagination-prev,
.ant-pagination-next {
  @apply flex items-center justify-center w-8 h-8 border rounded hover:border-blue-500 hover:text-blue-500;
}

.ant-pagination-item {
  @apply flex items-center justify-center w-8 h-8 border rounded;
}

.ant-pagination-item-active {
  @apply border-blue-500 text-blue-500;
}

.ant-select-selection-selected-value {
  @apply text-sm;
}

/* Style for page size dropdown */
.ant-pagination-options {
  @apply ml-4;
}

.ant-select-selector {
  @apply min-w-[90px] h-8 flex items-center;
}

/* Thêm style cho level badge nếu cần */
.level-badge {
  @apply px-2 py-1 rounded-full text-sm;
}
</style>
