<!-- Generated by Cursor -->
<template>
  <div class="flex border-b">
    <button 
      v-for="tab in tabs" 
      :key="tab.id"
      :class="[
        'px-4 py-2 border rounded-t-lg ',
        { 'bg-black text-white': modelValue === tab.id }
      ]"
      @click="$emit('update:modelValue', tab.id)"
    >
      {{ tab.label }}
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import type { TabType } from '@/types/profile'

export default defineComponent({
  name: 'ProfileTabs',

  props: {
    modelValue: {
      type: String as () => TabType,
      required: true
    }
  },

  emits: ['update:modelValue'],

  setup() {
    const tabs = [
      { id: 'date-join-member', label: 'Date Join Member' },
      { id: 'date-of-birth', label: 'Date of Birth' }
    ]

    return { tabs }
  }
})
</script>
