<!-- Generated by Cursor -->
<template>
  <div class="bg-white p-6 rounded-lg shadow-md mb-6">
    <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <!-- Date Range Picker for Date Join Member -->
      <template v-if="tab === 'date-join-member'">
        <div>
          <label class="block text-gray-700">Date Join Member</label>
          <a-form-item
          :rules="[{ required: true, message: 'Vui lòng chọn thời gian tham gia' }]"
          class="flex-1"
        >
          <a-range-picker
            v-model:value="dateRange"
            format="YYYY-MM-DD"
            :placeholder="['Start date', 'End date']"
            style="width: 100%; height: 40px;"
            :disabled-date="disabledDate"
            @change="onDateRangeChange"
          />
        </a-form-item>
        </div>
      </template>

      <!-- Month Selection for Date of Birth -->
      <template v-if="tab === 'date-of-birth'">
        <div>
          <label class="block text-gray-700">Select Birthday Month</label>
          <select 
            v-model="filters.birthMonth"
            class="w-full p-2 border rounded-lg"
          >
            <option v-for="month in months" :key="month.value" :value="month.value">
              {{ month.label }}
            </option>
          </select>
        </div>
      </template>
      
      <!-- Platform Website Filter -->
      <div>
        <label class="block text-gray-700 mb-2">Platform Website</label>
        <a-select
          v-model:value="filters.websiteId"
          style="width: 100%"
          placeholder="Select Platform"
          allow-clear
          @change="handleWebsiteChange"
        >
          <a-select-option value="">All Platforms</a-select-option>
          <a-select-option 
            v-for="website in websites" 
            :key="website.websiteId" 
            :value="website.websiteId"
          >
            {{ website.name }}
          </a-select-option>
        </a-select>
      </div>

      <!-- Member Level Filter -->
      <template v-if="tab === 'date-join-member'">
        <div>
          <label class="block text-gray-700">Member Level</label>
          <select 
            v-model="filters.levelId"
            class="w-full p-2 border rounded-lg"
            @change="handleFilter"
          >
            <option value="">All Levels</option>
            <option 
              v-for="level in memberLevels" 
              :key="level.levelId" 
              :value="level.levelId"
            >
              {{ level.Name }}
            </option>
          </select>
        </div>
      </template>

      <!-- Additional filters only for Date Join Member tab -->
      <template v-if="tab === 'date-join-member'">
        <div>
          <label class="block text-gray-700">Member Downgrade Month</label>
          <select 
            v-model="filters.memberDowngradeMonth"
            class="w-full p-2 border rounded-lg"
          >
            <option value="">Select month</option>
            <option v-for="month in months" :key="month.value" :value="month.value">
              {{ month.label }}
            </option>
          </select>
        </div>
      </template>
    </div>

    <div class="flex justify-end gap-4 mt-4">
      <button 
        @click="handleFilter"
        class="bg-blue-600 text-white py-2 px-4 rounded-lg"
      >
        Filter
      </button>
      <button 
        @click="handleReset"
        class="bg-gray-500 text-white py-2 px-4 rounded-lg"
      >
        Reset
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { websites, type Website } from '@/api/types/website'
import type { TabType } from '@/types/profile'
import { membershipAPI } from '@/api/services/membershipApi'
import dayjs from 'dayjs'

// Props & Emits
defineProps<{
  tab: TabType
}>()

const emit = defineEmits<{
  (e: 'filter', params: any): void
  (e: 'reset'): void
}>()

// State
const dateRange = ref<[dayjs.Dayjs, dayjs.Dayjs] | null>(null)
const memberLevels = ref<any[]>([])
const filters = ref({
  websiteId: '',
  levelId: '',
  memberDowngradeMonth: undefined,
  birthMonth: undefined
})
const loading = ref(false)

// Define months array
const months = ref(Array.from({ length: 12 }, (_, i) => ({
  value: i + 1,
  label: new Date(2000, i, 1).toLocaleString('default', { month: 'long' })
})))

// Methods
const handleWebsiteChange = (websiteId: number | '') => {
  // Reset levelId và cập nhật websiteId
  filters.value.levelId = ''
  filters.value.websiteId = websiteId

  handleFilter() // Gọi handleFilter để xử lý tất cả các filters
}

const handleFilter = () => {
  const searchParams = []
  
  // Xử lý filter website - Đảm bảo gửi đúng websiteId
  if (filters.value.websiteId !== '') {
    searchParams.push({
      key: 'websiteId',
      value: filters.value.websiteId.toString()
    })
  }

  // Xử lý date range
  if (dateRange.value) {
    const [startDate, endDate] = dateRange.value
    if (startDate && endDate) {
      searchParams.push(
        {
          key: 'registeredTimeFrom',
          value: startDate.format('YYYY-MM-DD')
        },
        {
          key: 'registeredTimeTo',
          value: endDate.format('YYYY-MM-DD')
        }
      )
    }
  }

  // Xử lý các filter khác
  if (filters.value.levelId) {
    searchParams.push({
      key: 'levelId',
      value: filters.value.levelId.toString()
    })
  }

  if (filters.value.memberDowngradeMonth) {
    searchParams.push({
      key: 'memberDowngradeMonth',
      value: filters.value.memberDowngradeMonth.toString()
    })
  }

  // Log để debug
  console.log('Filter params:', searchParams)
  console.log('Selected websiteId:', filters.value.websiteId)

  // Emit với đầy đủ thông tin
  emit('filter', {
    sortField: 'MembershipsWebsitesId',
    sortType: 'ASC',
    pageSize: 10,
    pageIndex: 1,
    searchParams
  })
}

// Reset function
const handleReset = () => {
  filters.value = {
    websiteId: '',
    levelId: '',
    memberDowngradeMonth: undefined,
    birthMonth: undefined
  }
  dateRange.value = null
  emit('reset')
}

// Lifecycle hooks
onMounted(async () => {
  try {
    const response = await membershipAPI.getLevelInfo()
    if (response?.code === 200 && response?.data) {
      memberLevels.value = response.data
    }
  } catch (error) {
    console.error('Error fetching member levels:', error)
  }
})

// Return all methods and refs that are used in template
const disabledDate = (current: dayjs.Dayjs) => {
  return current && current > dayjs().endOf('day')
}

const onDateRangeChange = (dates: [dayjs.Dayjs, dayjs.Dayjs] | null) => {
  if (dates) {
    const [startDate, endDate] = dates
    emit('filter', {
      registeredTimeFrom: startDate.format('YYYY-MM-DD'),
      registeredTimeTo: endDate.format('YYYY-MM-DD')
    })
  }
}

// Export all necessary methods and refs
defineExpose({
  dateRange,
  filters,
  websites,
  memberLevels,
  months,
  handleWebsiteChange,
  handleFilter,
  handleReset,
  disabledDate,
  onDateRangeChange
})
</script> 