<!-- Generated by Cursor -->
<template>
  <div class="bg-white p-6 rounded-lg shadow-md mb-6">
    <div class="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-4 gap-4">
      <!-- Date Range Picker for Date Join Member -->
      <template v-if="tab === 'date-join-member'">
        <div class="relative">
          <label class="block text-gray-700">Date Range</label>
          <div 
            @click="showDatePicker = !showDatePicker"
            class="w-full p-2 border rounded-lg cursor-pointer flex justify-between items-center"
          >
            <span>{{ formatDateRange }}</span>
            <i class="fas fa-calendar"></i>
          </div>
          
          <!-- Custom Date Picker Dropdown -->
          <div v-if="showDatePicker" class="absolute z-50 mt-1 bg-white rounded-lg shadow-lg border p-4">
            <div class="flex gap-4 mb-4">
              <div>
                <label class="block text-sm mb-1">Start Date</label>
                <input 
                  type="date" 
                  v-model="filters.startDate"
                  class="p-2 border rounded-lg"
                >
              </div>
              <div>
                <label class="block text-sm mb-1">End Date</label>
                <input 
                  type="date" 
                  v-model="filters.endDate"
                  class="p-2 border rounded-lg"
                >
              </div>
            </div>
            <div class="flex justify-end gap-2">
              <button 
                @click="cancelDateSelection"
                class="px-3 py-1 text-sm bg-gray-200 rounded-lg"
              >
                Cancel
              </button>
              <button 
                @click="confirmDateSelection"
                class="px-3 py-1 text-sm bg-purple-500 text-white rounded-lg"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      </template>

      <!-- Month Selection for Date of Birth -->
      <template v-if="tab === 'date-of-birth'">
        <div>
          <label class="block text-gray-700">Select Month</label>
          <select 
            v-model="filters.birthMonth"
            class="w-full p-2 border rounded-lg"
          >
            <option value="">Select month</option>
            <option v-for="month in months" :key="month.value" :value="month.value">
              {{ month.label }}
            </option>
          </select>
        </div>
      </template>
      
      <!-- Platform Website Filter (common for both tabs) -->
      <div>
        <label class="block text-gray-700">Platform Website</label>
        <select 
          v-model="filters.platformWebsite"
          class="w-full p-2 border rounded-lg"
        >
          <option value="All">All</option>
          <option v-for="platform in platforms" :key="platform" :value="platform">
            {{ platform }}
          </option>
        </select>
      </div>

      <!-- Additional filters only for Date Join Member tab -->
      <template v-if="tab === 'date-join-member'">
        <div>
          <label class="block text-gray-700">Order Point</label>
          <input 
            type="number" 
            v-model="filters.orderPoint"
            class="w-full p-2 border rounded-lg" 
            placeholder="Enter points"
          >
        </div>
        <div>
          <label class="block text-gray-700">Level Up Condition</label>
          <input 
            type="text" 
            v-model="filters.levelUpCondition"
            class="w-full p-2 border rounded-lg"
            placeholder="Enter condition"
          >
        </div>
        <div>
          <label class="block text-gray-700">Member Downgrade Month</label>
          <select 
            v-model="filters.memberDowngradeMonth"
            class="w-full p-2 border rounded-lg"
          >
            <option value="">Select month</option>
            <option v-for="month in months" :key="month.value" :value="month.value">
              {{ month.label }}
            </option>
          </select>
        </div>
      </template>
    </div>

    <div class="flex justify-end gap-4 mt-4">
      <button 
        @click="handleFilter"
        class="bg-blue-600 text-white py-2 px-4 rounded-lg"
      >
        Filter
      </button>
      <button 
        @click="handleReset"
        class="bg-gray-500 text-white py-2 px-4 rounded-lg"
      >
        Reset
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, reactive, ref } from 'vue'
import type { TabType, FilterParams, PlatformWebsite } from '@/types/profile'

export default defineComponent({
  name: 'SearchFilters',

  props: {
    tab: {
      type: String as () => TabType,
      required: true
    }
  },

  emits: ['filter', 'reset'],

  setup(props, { emit }) {
    const filters = reactive<FilterParams>({})
    const showDatePicker = ref(false)
    const tempDates = reactive({
      startDate: '',
      endDate: ''
    })
    
    const platforms: PlatformWebsite[] = ['hince', 'BBIA', 'mixsoon', 'sky007']
    
    const months = Array.from({ length: 12 }, (_, i) => ({
      value: i + 1,
      label: new Date(2000, i, 1).toLocaleString('default', { month: 'long' })
    }))

    const formatDateRange = computed(() => {
      if (!filters.startDate && !filters.endDate) return 'Select Date Range'
      
      const start = filters.startDate ? new Date(filters.startDate).toLocaleDateString() : ''
      const end = filters.endDate ? new Date(filters.endDate).toLocaleDateString() : ''
      return `${start} - ${end}`
    })

    const cancelDateSelection = () => {
      showDatePicker.value = false
    }

    const confirmDateSelection = () => {
      showDatePicker.value = false
    }

    const handleFilter = () => {
      emit('filter', { ...filters })
    }

    const handleReset = () => {
      Object.keys(filters).forEach(key => {
        filters[key as keyof FilterParams] = undefined
      })
      emit('reset')
    }

    return {
      filters,
      platforms,
      months,
      showDatePicker,
      formatDateRange,
      cancelDateSelection,
      confirmDateSelection,
      handleFilter,
      handleReset
    }
  }
})
</script> 