<!-- Generated by Cursor -->
<template>
  <div class="bg-white p-6 rounded-lg shadow mb-6">
    <a-form layout="vertical" :model="filterForm">
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
        <!-- Date Join Member Tab -->
        <template v-if="tab === 'date-join-member'">
          <!-- Date Join Member Range -->
          <a-form-item :label="t('profileManagement.filter.dateJoinMember')">
            <a-range-picker
              v-model:value="filterForm.registeredTimeRange"
              style="width: 100%"
            />
          </a-form-item>

          <!-- Platform Website -->
          <a-form-item :label="t('profileManagement.filter.platformWebsite')">
            <a-select v-model:value="filterForm.websiteId">
              <a-select-option value="">{{ t('profileManagement.filter.allWebsites') }}</a-select-option>
              <a-select-option v-for="website in websites" 
                              :key="website.websiteId" 
                              :value="website.websiteId">
                {{ website.name }}
              </a-select-option>
            </a-select>
          </a-form-item>

          <!-- Member Level -->
          <a-form-item :label="t('profileManagement.filter.memberLevel')">
            <a-select v-model:value="filterForm.levelId">
              <a-select-option value="">{{ t('profileManagement.filter.allLevels') }}</a-select-option>
              <a-select-option v-for="level in memberLevels" :key="level.id" :value="level.id">
                {{ level.levelName }}
              </a-select-option>
            </a-select>
          </a-form-item>
        </template>

        <!-- Date of Birth Tab -->
        <template v-else-if="tab === 'date-of-birth'">
          <!-- Date of Birth Range -->
          <a-form-item :label="t('profileManagement.filter.dateOfBirth')">
            <a-range-picker
              v-model:value="filterForm.birthdayRange"
              style="width: 100%"
            />
          </a-form-item>

          <!-- Platform Website -->
          <a-form-item :label="t('profileManagement.filter.platformWebsite')">
            <a-select v-model:value="filterForm.websiteId">
              <a-select-option value="">{{ t('profileManagement.filter.allWebsites') }}</a-select-option>
              <a-select-option v-for="website in websites" 
                              :key="website.websiteId" 
                              :value="website.websiteId">
                {{ website.name }}
              </a-select-option>
            </a-select>
          </a-form-item>
        </template>

        <!-- History Tab -->
        <template v-else-if="tab === 'history'">
          <a-form-item :label="t('profileManagement.filter.purchaseDate')">
            <a-range-picker
              v-model:value="filterForm.purchaseDateRange"
              style="width: 100%"
            />
          </a-form-item>

          <a-form-item :label="t('profileManagement.filter.platformWebsite')">
            <a-select v-model:value="filterForm.websiteId">
              <a-select-option value="">{{ t('profileManagement.filter.allWebsites') }}</a-select-option>
              <a-select-option v-for="website in websites" 
                              :key="website.websiteId" 
                              :value="website.websiteId">
                {{ website.name }}
              </a-select-option>
            </a-select>
          </a-form-item>
        </template>
      </div>

      <!-- Action Buttons -->
      <div class="flex justify-end space-x-4 mt-4">
        <a-button type="primary" @click="handleSearch">{{ t('profileManagement.filter.filterButtonText') }}</a-button>
        <a-button @click="handleReset">{{ t('profileManagement.filter.reset') }}</a-button>
      </div>
    </a-form>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useI18nGlobal } from '@/i18n'
import type { Dayjs } from 'dayjs'
import type { TabType } from '@/types/profile'
import { websites } from '@/api/types/website'
import { memberLevels, getLevelNameById } from '@/api/types/member'

const { t } = useI18nGlobal()

const props = defineProps<{
  tab: TabType
}>()

const emit = defineEmits<{
  (e: 'filter', params: Array<{key: string, value: any}>): void
  (e: 'reset'): void
}>()

interface FilterForm {
  registeredTimeRange: [Dayjs, Dayjs] | null
  birthdayRange: [Dayjs, Dayjs] | null
  websiteId: string | number
  levelId: string | number
  purchaseDateRange: [Dayjs, Dayjs] | null
}

const filterForm = reactive<FilterForm>({
  registeredTimeRange: null,
  birthdayRange: null,
  websiteId: '',
  levelId: '',
  purchaseDateRange: null
})

const handleSearch = () => {
  const params: Array<{key: string, value: any}> = []

  if (props.tab === 'history') {
    if (filterForm.purchaseDateRange?.[0] && filterForm.purchaseDateRange?.[1]) {
      params.push({ 
        key: 'orderDateFrom', 
        value: filterForm.purchaseDateRange[0].format('YYYY-MM-DD') 
      })
      params.push({ 
        key: 'orderDateTo', 
        value: filterForm.purchaseDateRange[1].format('YYYY-MM-DD') 
      })
    }
    if (filterForm.websiteId) {
      params.push({ 
        key: 'websiteId', 
        value: filterForm.websiteId.toString()
      })
    }
  } else if (props.tab === 'date-join-member') {
    // 1. Date Join Member Range
    if (filterForm.registeredTimeRange?.[0] && filterForm.registeredTimeRange?.[1]) {
      const startDate = filterForm.registeredTimeRange[0]
      const endDate = filterForm.registeredTimeRange[1]
      
      if (startDate.isValid() && endDate.isValid()) {
        params.push({ 
          key: 'registeredTimeFrom', 
          value: startDate.format('YYYY-MM-DD') 
        })
        params.push({ 
          key: 'registeredTimeTo', 
          value: endDate.format('YYYY-MM-DD') 
        })
      }
    }

    // 2. Member Level (giữ nguyên cách filter theo levelName)
    if (filterForm.levelId) {
      const levelName = getLevelNameById(Number(filterForm.levelId))
      if (levelName) {
        params.push({ 
          key: 'levelName', 
          value: levelName.trim()
        })
      }
    }
  } else if (props.tab === 'date-of-birth') {
    // Date of Birth Range
    if (filterForm.birthdayRange) {
      params.push({ 
        key: 'birthdayFrom', 
        value: filterForm.birthdayRange[0].format('YYYY-MM-DD') 
      })
      params.push({ 
        key: 'birthdayTo', 
        value: filterForm.birthdayRange[1].format('YYYY-MM-DD') 
      })
    }
  }

  if (params.length > 0) {
    emit('filter', params)
  } else {
    emit('reset')
  }
}

const handleReset = () => {
  if (props.tab === 'history') {
    filterForm.purchaseDateRange = null
    filterForm.websiteId = ''
  } else {
    Object.assign(filterForm, {
      registeredTimeRange: null,
      birthdayRange: null,
      websiteId: '',
      levelId: ''
    })
  }
  emit('reset')
}
</script>