<!-- Generated by Cursor -->
<template>
  <div class="mb-6">
    <div class="overflow-x-auto">
      <table class="min-w-full bg-white shadow rounded">
        <thead class="bg-gray-50">
          <tr>
            <th class="py-3 px-4 border-b text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Tên Cấp Bậc
            </th>
            <th class="py-3 px-4 border-b text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Số Tiền Ngưỡng
            </th>
            <th class="py-3 px-4 border-b text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Thời Hạn
            </th>
            <th class="py-3 px-4 border-b text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Dịch Vụ Đặc Biệt
            </th>
            <th class="py-3 px-4 border-b text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
              Thao Tác
            </th>
          </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
          <tr v-for="rule in rules" :key="rule.levelId">
            <td class="py-4 px-4 whitespace-nowrap">{{ rule.Name }}</td>
            <td class="py-4 px-4 whitespace-nowrap">
              {{ formatCurrency(rule.thresholdAmount) }}
            </td>
            <td class="py-4 px-4 whitespace-nowrap">
              {{ rule.durationExpired }} tháng
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
            <div class="flex items-center justify-end space-x-2">
              <!-- Edit Button -->
              <button
                @click="$emit('edit', rule)"
                class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
              >
                <svg 
                  class="h-4 w-4 mr-1.5" 
                  fill="none" 
                  stroke="currentColor" 
                  viewBox="0 0 24 24"
                >
                  <path 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    stroke-width="2" 
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>
                Sửa
              </button>

              <!-- Delete Button -->
              <button
                @click="$emit('delete', rule)"
                class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors duration-200"
              >
                <svg 
                  class="h-4 w-4 mr-1.5" 
                  fill="none" 
                  stroke="currentColor" 
                  viewBox="0 0 24 24"
                >
                  <path 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    stroke-width="2" 
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
                Xóa
              </button>
              </div>
            </td>
          </tr>
          <tr v-if="!rules.length">
            <td colspan="5" class="py-4 px-4 text-center text-gray-500">
              Chưa có quy tắc nào
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { EditOutlined, DeleteOutlined } from '@ant-design/icons-vue';
import type { LevelSetting } from '@/types/levelUpDownRules';

defineProps<{
  rules: LevelSetting[];
}>();

defineEmits<{
  (e: 'edit', rule: LevelSetting): void;
  (e: 'delete', rule: LevelSetting): void;
}>();

const formatCurrency = (value: number): string => {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND'
  }).format(value);
};
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
