<!-- Generated by Cursor -->
<template>
  <div class="overflow-x-auto">
    <table class="min-w-full divide-y divide-gray-200">
      <thead class="bg-gray-50">
        <tr>
          <!-- <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
            Cấp Bậc
          </th> -->
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Cấp Bậc
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Số tiền tích lũy tối thiểu (VNĐ)
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Tỷ Lệ Tích Điểm (%)
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Tỷ Lệ Đổi Điểm (%)
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Thời Hạn Hiệu Lực (Tháng)
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Giảm Giá (%)
          </th>
          <th scope="col" class="py-2 px-4 border-b text-left text-gray-600">
            Actions
          </th>
          <!-- <th scope="col" class="relative px-6 py-3">
            <span class="sr-only">Actions</span>
          </th> -->
        </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        <tr v-for="benefit in benefits" :key="benefit.levelId">
          <!-- <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.rank }}
          </td> -->
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.Name }}
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.thresholdAmount }}
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.rewardRate }}%
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.redeemRate }}%
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.durationExpired || 'Không giới hạn' }}
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
            {{ benefit.discountPerOrder }}%
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
            <div class="flex items-center justify-end space-x-2">
              <!-- Edit Button -->
              <button
                @click="handleEdit(benefit)"
                class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
              >
                <svg 
                  class="h-4 w-4 mr-1.5" 
                  fill="none" 
                  stroke="currentColor" 
                  viewBox="0 0 24 24"
                >
                  <path 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    stroke-width="2" 
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>
                Sửa
              </button>

              <!-- Delete Button -->
              <button
                @click="handleDelete(benefit.levelId)"
                class="inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-red-700 bg-red-100 hover:bg-red-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors duration-200"
              >
                <svg 
                  class="h-4 w-4 mr-1.5" 
                  fill="none" 
                  stroke="currentColor" 
                  viewBox="0 0 24 24"
                >
                  <path 
                    stroke-linecap="round" 
                    stroke-linejoin="round" 
                    stroke-width="2" 
                    d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                  />
                </svg>
                Xóa
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>

    <!-- Empty State -->
    <div 
      v-if="benefits.length === 0" 
      class="text-center py-12 bg-gray-50"
    >
      <svg
        class="mx-auto h-12 w-12 text-gray-400"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
        />
      </svg>
      <h3 class="mt-2 text-sm font-medium text-gray-900">Không có dữ liệu</h3>
      <p class="mt-1 text-sm text-gray-500">Bắt đầu bằng cách thêm cấp bậc mới.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, type PropType } from 'vue'
import type { LevelSetting } from '@/data/benefits'

export default defineComponent({
  name: 'BenefitTable',

  props: {
    benefits: {
      type: Array as PropType<LevelSetting[]>,
      required: true
    }
  },

  emits: ['edit', 'delete'],

  setup(props, { emit }) {
    const handleEdit = (benefit: LevelSetting) => {
      emit('edit', benefit)
    }

    const handleDelete = (levelId: number) => {
      emit('delete', levelId)
    }

    return {
      handleEdit,
      handleDelete
    }
  }
})
</script>

<style scoped>
/* Hover effect for table rows */
tr:hover {
  background-color: rgba(249, 250, 251, 0.5);
}

/* Transition for buttons */
button {
  transition: all 0.2s ease-in-out;
}

button:hover {
  transform: translateY(-1px);
}

button:active {
  transform: translateY(0);
}
</style>
