// Generated by Cursor
import axiosInstance from './config/axios';
import type { LoginCredentials, RegisterCredentials, AuthResponse } from '@/types/auth';

export const authApi = {
  async login(credentials: LoginCredentials): Promise<AuthResponse> {
    try {
      const response = await axiosInstance.post<AuthResponse>(
        '/membership/login',
        credentials,
        {
          headers: {
            'Content-Type': 'application/json'
          }
        }
      );
      return response.data;
    } catch (error: any) {
      console.error('Login API error:', error);
      throw error;
    }
  },

  async register(credentials: RegisterCredentials): Promise<AuthResponse> {
    try {
      const response = await axiosInstance.post<AuthResponse>(
        '/membership/register',
        credentials
      );
      return response.data;
    } catch (error: any) {
      console.error('Register API error:', error);
      throw error;
    }
  },

  async logout(): Promise<void> {
    try {
      await axiosInstance.post('/membership/logout');
    } catch (error: any) {
      console.warn('Logout API failed:', error);
      throw error;
    }
  }
};

export default axiosInstance;
// End Generated by Cursor