<!-- Code generated by Cursor -->
<template>
  <DefaultLayout>
    <div class="flex-1 p-6 overflow-auto">
      <h2 class="text-3xl font-bold mb-6">Level Analysis</h2>

      <div class="mb-8 flex items-center">
        <label class="text-gray-700 font-medium mr-4">Chọn Thương Hiệu:</label>
        <select 
          v-model="selectedBrand"
          class="block w-1/3 bg-white border border-gray-300 rounded px-4 py-2"
        >
          <option 
            v-for="website in WEBSITES"
            :key="website.WebsiteId"
            :value="website.WebsiteId"
          >
            {{ website.Name }}
          </option>
        </select>
      </div>

      <MemberStatistics :statistics="memberStats" />
      <TransitionChart :brand="selectedBrand" />
      <BehaviorChart :brand="selectedBrand" />
    </div>
  </DefaultLayout>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, watch } from 'vue'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import { initialMemberStats } from '@/data/analysisMemberData'
import MemberStatistics from '@/components/MemberAnalysis/LevelAnalysis/MemberStatistic.vue'
import TransitionChart from '@/components/MemberAnalysis/LevelAnalysis/TransitionChart.vue'
import BehaviorChart from '@/components/MemberAnalysis/LevelAnalysis/BehaviorChart.vue'
import { levelService as rankService } from '@/api/services/levelService'
import { message } from 'ant-design-vue'
import dayjs, { type Dayjs } from 'dayjs'
// Định nghĩa interface và constant cho websites
interface Website {
  WebsiteId: string;
  Name: string;
}

const WEBSITES: Website[] = [
  {
    WebsiteId: "1",
    Name: "Sky007",
  },
  {
    WebsiteId: "2",
    Name: "Bbia",
  },
  {
    WebsiteId: "3",
    Name: "Hince",
  },
  {
    WebsiteId: "4",
    Name: "Mixsoon",
  }
]

const loading = ref(false)
const dateRange = ref<[Dayjs, Dayjs]>([
  dayjs().startOf('year'),
  dayjs().endOf('year')
])

export default defineComponent({
  name: 'LevelAnalysis',

  components: {
    DefaultLayout,
    MemberStatistics,
    TransitionChart,
    BehaviorChart
  },

  setup() {
    // Khởi tạo selectedBrand với giá trị mặc định là website đầu tiên
    const selectedBrand = ref(WEBSITES[0].WebsiteId)
    const memberStats = ref({
      'Diamond': 0,
      'Gold': 0,
      'Silver': 0
    })

    const fetchRankStatistics = async () => {
      try {
        loading.value = true
        const [startDate, endDate] = dateRange.value

        const response = await rankService.getRankStatistics(selectedBrand.value, {
          startDate: startDate.format('YYYY-MM-DD'),
          endDate: endDate.format('YYYY-MM-DD')
        })

        // Reset về 0
        memberStats.value = {
          'Diamond': 0,
          'Gold': 0, 
          'Silver': 0
        }

        // Cập nhật giá trị từ API
        if (response && Array.isArray(response)) {
          response.forEach(item => {
            if (item.level_name === 'Diamond') {
              memberStats.value.Diamond = item.total_members
            } else if (item.level_name === 'Silver') {
              memberStats.value.Silver = item.total_members
            } else
              memberStats.value.Gold = item.total_members

          })
        }

      } catch (error) {
        console.error('Error fetching rank statistics:', error)
        message.error('Không thể tải dữ liệu thống kê hạng thành viên')
      } finally {
        loading.value = false
      }
    }

    // Add watchers
    watch([selectedBrand, dateRange], () => {
      fetchRankStatistics()
    })

    // Add mounted hook
    onMounted(() => {
      fetchRankStatistics()
    })

    return {
      selectedBrand,
      memberStats,
      WEBSITES
    }
  }
})
</script>
