<!-- Code generated by Cursor -->
<template>
  <DefaultLayout>
    <div class="flex-1 p-6 overflow-auto">
      <h2 class="text-3xl font-bold mb-6">{{ t('levelAnalysis.title') }}</h2>

      <div class="mb-8 flex items-center">
        <label class="text-gray-700 font-medium mr-4">{{ t('levelAnalysis.brand.label') }}</label>
        <select 
          v-model="selectedBrand"
          class="block w-1/3 bg-white border border-gray-300 rounded px-4 py-2"
        >
          <option 
            v-for="website in WEBSITES"
            :key="website.WebsiteId"
            :value="website.WebsiteId"
          >
            {{ website.Name }}
          </option>
        </select>
      </div>

      <MemberStatistics :statistics="memberStats" />
      <TransitionChart :brand="selectedBrand" />
      <BehaviorChart :brand="selectedBrand" />
    </div>
  </DefaultLayout>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { useI18nGlobal } from '@/i18n'
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import MemberStatistics from '@/components/MemberAnalysis/LevelAnalysis/MemberStatistic.vue'
import TransitionChart from '@/components/MemberAnalysis/LevelAnalysis/TransitionChart.vue'
import BehaviorChart from '@/components/MemberAnalysis/LevelAnalysis/BehaviorChart.vue'
import { levelService as rankService } from '@/api/services/levelService'
import { message } from 'ant-design-vue'
import dayjs, { type Dayjs } from 'dayjs'

const { t } = useI18nGlobal()

// Define interface and constant for websites
interface Website {
  WebsiteId: string;
  Name: string;
}

const WEBSITES: Website[] = [
  {
    WebsiteId: "1",
    Name: t('levelAnalysis.brand.options.sky007'),
  },
  {
    WebsiteId: "2",
    Name: t('levelAnalysis.brand.options.bbia'),
  },
  {
    WebsiteId: "3",
    Name: t('levelAnalysis.brand.options.hince'),
  },
  {
    WebsiteId: "4",
    Name: t('levelAnalysis.brand.options.mixsoon'),
  }
]

const loading = ref(false)
const dateRange = ref<[Dayjs, Dayjs]>([
  dayjs().startOf('year'),
  dayjs().endOf('year')
])

// Initialize selectedBrand with the first website as default value
const selectedBrand = ref(WEBSITES[0].WebsiteId)
const memberStats = ref({
  [t('levelAnalysis.levels.diamond')]: 0,
  [t('levelAnalysis.levels.gold')]: 0,
  [t('levelAnalysis.levels.silver')]: 0
})

const fetchRankStatistics = async () => {
  try {
    loading.value = true
    const [startDate, endDate] = dateRange.value

    const response = await rankService.getRankStatistics(selectedBrand.value, {
      startDate: startDate.format('YYYY-MM-DD'),
      endDate: endDate.format('YYYY-MM-DD')
    })

    // Reset to 0
    memberStats.value = {
      [t('levelAnalysis.levels.diamond')]: 0,
      [t('levelAnalysis.levels.gold')]: 0,
      [t('levelAnalysis.levels.silver')]: 0
    }

    // Update values from API
    if (response && Array.isArray(response)) {
      response.forEach(item => {
        if (item.level_name === t('levelAnalysis.levels.diamond')) {
          memberStats.value[t('levelAnalysis.levels.diamond')] = item.total_members
        } else if (item.level_name === t('levelAnalysis.levels.silver')) {
          memberStats.value[t('levelAnalysis.levels.silver')] = item.total_members
        } else {
          memberStats.value[t('levelAnalysis.levels.gold')] = item.total_members
        }
      })
    }

  } catch (error) {
    console.error('Error fetching rank statistics:', error)
    message.error(t('levelAnalysis.messages.error.loadStats'))
  } finally {
    loading.value = false
  }
}

// Add watchers
watch([selectedBrand, dateRange], () => {
  fetchRankStatistics()
})

// Add mounted hook
onMounted(() => {
  fetchRankStatistics()
})
</script>
