<!-- Refactor by cusor-->
 <!-- Generated by Cursor -->
<!-- <script setup lang="ts">
import { RouterView } from 'vue-router'
</script> -->

<template>
  <div id="app">
    <!-- Fix bug cursor -->
    <!-- <nav v-if="authStore.isAuthenticated">
      <router-link to="/">Trang chủ</router-link>
      <a href="#" @click.prevent="handleLogout" class="logout-link">
        {{ authStore.loading ? 'Đang đăng xuất...' : 'Đăng xuất' }}
      </a>
    </nav> -->

    <router-view></router-view>
  </div>
</template>
<script lang="ts">
import { defineComponent, onMounted } from 'vue';
import { useAuthStore } from '@/stores/auth';
import DropdownUser from '@/components/Header/DropdownUser.vue';

export default defineComponent({
  name: 'App',
  components: {
    DropdownUser
  },
  setup() {
    const authStore = useAuthStore();

    onMounted(async () => {
      // Khởi tạo auth và fetch user info
      await authStore.initializeAuth();
    });

    const handleLogout = async () => {
      try {
        await authStore.logout();
      } catch (error) {
        console.error('Logout error:', error);
        // Có thể thêm thông báo lỗi cho người dùng ở đây
      }
    };

    return {
      authStore,
      handleLogout
    };
  }
});
</script>
