<template>
  <DefaultLayout>
    <div class="bg-white p-6 rounded-lg shadow-md">
      <h1 class="text-2xl font-bold text-center mb-8">Purchase History</h1>
      
      <PurchaseHistoryFilters
        @filter="handleFilterChange"
        @reset="handleReset"
      />

      <!-- Loading state -->
      <div v-if="loading" class="text-center py-4">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
        <p class="mt-2">Loading purchase history...</p>
      </div>

      <!-- Error state -->
      <div v-else-if="error" class="text-center py-4 text-red-600">
        {{ error }}
      </div>

      <!-- Data table -->
      <template v-else>
        <table class="w-full border-collapse border border-gray-300 mt-4">
          <thead class="bg-gray-100">
            <tr>
              <th class="border border-gray-300 p-2">Order ID Website</th>
              <th class="border border-gray-300 p-2">Create Time</th>
              <th class="border border-gray-300 p-2">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="order in orders" :key="order.orderId">
              <td class="border border-gray-300 p-2">{{ order.orderIdWebsite }}</td>
              <td class="border border-gray-300 p-2">{{ formatDate(order.createTime) }}</td>
              <td class="border border-gray-300 p-2">
                <span 
                  :class="getStatusClass(order.status)"
                  class="px-2 py-1 rounded-full text-sm"
                >
                  {{ order.orderStatus }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </template>
    </div>
  </DefaultLayout>
</template>

<script lang="ts">
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import { defineComponent, ref } from 'vue'
import { formatDate } from '@/utils/date'
import { purchaseApi } from '@/api/services/purchaseApi'
import PurchaseHistoryFilters from '@/components/PurchaseHistory/PurchaseHistoryFilters.vue'

export default defineComponent({
  components: {
    DefaultLayout,
    PurchaseHistoryFilters
  },

  name: 'PurchaseHistory',

  setup() {
    const orders = ref<PurchaseHistory[]>([])
    const loading = ref(false)
    const error = ref<string | null>(null)
    const currentFilters = ref<Record<string, string>>({})

    const fetchOrders = async (filters: Record<string, string> = {}) => {
      loading.value = true
      try {
        const response = await purchaseApi.getPurchaseHistory(filters)
        orders.value = response.data
      } catch (err) {
        error.value = 'Failed to load purchase history'
        console.error(err)
      } finally {
        loading.value = false
      }
    }

    const formatAmount = (amount: number) => {
      return new Intl.NumberFormat('vi-VN', {
        style: 'currency',
        currency: 'VND'
      }).format(amount)
    }

    const getStatusClass = (status: string) => {
      const classes = {
        'Completed': 'bg-green-100 text-green-800',
        'Pending': 'bg-yellow-100 text-yellow-800',
        'Cancelled': 'bg-red-100 text-red-800'
      }
      return classes[status as keyof typeof classes] || 'bg-gray-100 text-gray-800'
    }

    const handleFilterChange = (filters: Record<string, string>) => {
      currentFilters.value = filters
      fetchOrders(filters)
    }

    const handleReset = () => {
      currentFilters.value = {}
      fetchOrders()
    }

    return {
      orders,
      loading,
      error,
      formatDate,
      formatAmount,
      getStatusClass,
      handleFilterChange,
      handleReset
    }
  }
})
</script>
  
  <style scoped>
  .purchase-history {
    max-width: 1000px;
    margin: 0 auto;
    padding: 20px;
  }
  
  .purchase-history h1 {
    text-align: center;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
  }
  
  th, td {
    text-align: left;
  }
  
  th {
    background-color: #f9fafb;
  }
  
  tr:nth-child(even) {
    background-color: #f2f2f2;
  }
  
  button:disabled {
    cursor: not-allowed;
  }
  </style>
  <!-- End all code generated by Cursor -->